name: Build Android

on:
  workflow_dispatch:
    inputs:
      base_number:
        description: 'Base build number'
        required: false
        default: -1
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.get-build.outputs.build-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Get build number
        id: get-build
        uses: mlilback/build-number@v1
        with:
          base: ${{ inputs.base_number }}
          run-id: ${{ github.run_number }}

      - name: Creating Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > /tmp/keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > android/keystore.properties
          echo storeFile=/tmp/keystore.jks >> android/keystore.properties
          echo "versionCode=${{ steps.get-build.outputs.build-number }}" >> android/build-key.properties
          echo "versionName=${{ vars.BUILD_NAME }}" >> android/build-key.properties

      - name: Create Google Services file
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Set outputs
        id: set-outputs
        run: echo "build-number=${{ steps.get-build.outputs.build-number }}" >> $GITHUB_OUTPUT

  create-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release name
        id: get-release
        run: echo "RELEASE=v${{ vars.BUILD_NAME }}(${{ needs.build.outputs.build-number }})" >> $GITHUB_OUTPUT

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          skip-version-file: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        # if there is no tag, don't create a release
        if: ${{ steps.changelog.outputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ github.sha }}
          tag_name: '${{ steps.changelog.outputs.tag }}'
          name: 'release/${{ steps.get-release.outputs.RELEASE }}'
          body: ${{ steps.changelog.outputs.clean_changelog }}
